### ISSUE TITLE
Gelera Cluster creation failing from Ansible

### ISSUE THREAD

**Issue by thespacedoctor** [severalnines/ansible-clustercontrol#11]
Seems the JSON command needs updating to replace `mysql_hostnames` with `nodes`. From ansible:

```json
...
"mysql_hostname": [
      "165.22.125.206",
      "178.62.41.5",
      "167.71.143.229"
    ],
    "mysql_hostnames": [
      "165.22.125.206",
      "178.62.41.5",
      "167.71.143.229"
    ]
```

but the UI generates the following instead:

```json
...
"nodes": [
      {
        "hostname": "10.131.21.159",
        "hostname_data": "10.131.21.159",
        "hostname_internal": "",
        "port": "3306"
      },
      {
        "hostname": "10.131.21.160",
        "hostname_data": "10.131.21.160",
        "hostname_internal": "",
        "port": "3306"
      },
      {
        "hostname": "10.131.21.161",
        "hostname_data": "10.131.21.161",
        "hostname_internal": "",
        "port": "3306"
      }
    ]
```

This would explain why the Ansible job log looks like this:

```text
[11:17:42]: Setting up the first server failed, aborting.
 [11:17:42]: wsrep_cluster_address = 'gcomm://'
 [11:17:42]: Creating the cluster with the following:
 [11:17:42]: Verifying job parameters.
 [11:17:42]: Cluster will be created on 0 data node(s).
```

**Comment by thespacedoctor** [comment]
Job ran successfully once I added the `nodes` parameter in the ansible role, but also needed to switch out `mysql_cnf_template: "my.cnf.galera"` for `mysql_cnf_template: "my.cnf.mdb10x-galera"`.

**Comment by ashraf-s9s** [comment]
Hi @thespacedoctor ,

Is this related to this:
https://github.com/severalnines/ansible-clustercontrol/blob/master/tasks/deploy-database.yml#L141

Where we need to change from: 
`          mysql_hostname: "{{ createg.mysql_hostnames }}"`
To:
`          nodes: "{{ createg.mysql_hostnames }}"`

Regarding `mysql_cnf_template`, did you deploy a MariaDB Galera Cluster or a Percona XtraDB Cluster? I am currently on mobile and have very limited resources to test at the moment.

**Comment by thespacedoctor** [comment]
> Is this related to this: https://github.com/severalnines/ansible-clustercontrol/blob/master/tasks/deploy-database.yml#L141

Yes. To get it working I just added a new `nodes` key-value:

```yaml
- name: Post create new Galera Cluster operation to ClusterControl.
  uri:
    url: "{{ rpc_url }}/0/job"
    method: POST
    body:
      token: "{{ rpc_token }}"
      operation: "createJob"
      job:
        command: "create_cluster"
        job_data:
          api_id: "{{ createg.api_id | default(1) }}"
          cluster_type: "galera"
          cluster_name: "{{ createg.cluster_name | default('gelara_cluster') }}"
          create_local_repository: "{{ createg.create_local_repository | default(false) }}"
          data_center: "{{ createg.data_center | default(0) }}"
          disable_firewall: "{{ createg.disable_firewall | default(true) }}"
          disable_selinux:  "{{ createg.disable_selinux | default(true) }}"
          enable_mysql_uninstall: "{{ createg.enable_mysql_uninstall | default(true) }}"
          generate_token: "{{ createg.generate_token | default(true) }}"
          mysql_cnf_template: "{{ createg.mysql_cnf_template | default('my.cnf.galera') }}"
          mysql_datadir: "{{ createg.mysql_datadir | default('/var/lib/mysql') }}"
          mysql_hostname: "{{ createg.mysql_hostnames }}"
          mysql_hostnames: "{{ createg.mysql_hostnames }}"
          mysql_password: "{{ createg.mysql_password | default('password') }}"
          mysql_port: "{{ createg.mysql_port | default(3306) }}"
          mysql_version: "{{ createg.mysql_version | default('5.6') }}"
          software_package: "{{ createg.software_package | default('') }}"
          ssh_keyfile: "{{ createg.ssh_keyfile | default('/root/.ssh/id_rsa') }}"
          ssh_port: "{{ createg.ssh_port | default(22) }}"
          ssh_user: "{{ createg.ssh_user | default('root') }}"
          sudo_password: "{{ createg.sudo_password }}"
          type: "{{ createg.type | default('mysql') }}"
          use_internal_repos: "{{ createg.use_internal_repos | default(false) }}"
          user_id: "{{ createg.user_id | default(1) }}"
          vendor: "{{ createg.vendor }}"
          nodes: "{{ createg.nodes }}"
    body_format: json
    return_content: yes
  with_items: "{{ cc_cluster }}"
  when:
    createg.operation == "create" and
    createg.cluster_type == "galera" and
    createg.deployment
  loop_control:
    loop_var: createg
```

I also did the same for the `Post add existing Galera Cluster operation to ClusterControl.` block.

I guess the better way would be to take `mysql_hostnames` and expand it in the role into the format `nodes` is expected in - but i took the path of least resistance :)

Then in the playbook I added the nodes like so:

```yaml
cc_cluster:
        nodes: 
            - hostname: "XXXXXXX"
              hostname_data: "XXXXXXX"
              hostname_internal: ""
              port: "3306"
            - hostname: "XXXXXXX"
              hostname_data: "XXXXXXX"
              hostname_internal: ""
              port: "3306"
            - hostname: "XXXXXXX"
              hostname_data: "XXXXXXX"
              hostname_internal: ""
              port: "3306"
```

> Regarding mysql_cnf_template, did you deploy a MariaDB Galera Cluster or a Percona XtraDB Cluster?

It was a MariaDB Galera Cluster.
