### ISSUE TITLE
On Ubuntu, deploying fails due to missing PyMySQL module

### ISSUE THREAD

**Issue by optimadba** [severalnines/ansible-clustercontrol#12]
Deploying against Ubuntu18.04 fails when attempting to remove the MySQL test database:

TASK [severalnines.clustercontrol : Remove MySQL test database.] ***************************************************************************
fatal: [192.168.56.110]: FAILED! => {"changed": false, "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}

I worked around this issue by adding the following lines to setup-debian.yml:

- name: Making sure MySQL Python helper libraries are installed.
  apt: name=python-pymysql state=present
  when:
    ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 18

- name: Making sure MySQL Python3 helper libraries are installed.
  apt: name=python3-pymysql state=present
  when:
    ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 18

Perhaps this can be added to the repo?

**Comment by bharathmsd7** [comment]
Facing the same issue while installing in Ubuntu 18.04
Any solution for this issue.

**Comment by bharathmsd7** [comment]
> Deploying against Ubuntu18.04 fails when attempting to remove the MySQL test database:
> 
> TASK [severalnines.clustercontrol : Remove MySQL test database.] ***************************************************************************
> fatal: [192.168.56.110]: FAILED! => {"changed": false, "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
> 
> I worked around this issue by adding the following lines to setup-debian.yml:
> 
> * name: Making sure MySQL Python helper libraries are installed.
>   apt: name=python-pymysql state=present
>   when:
>   ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 18
> * name: Making sure MySQL Python3 helper libraries are installed.
>   apt: name=python3-pymysql state=present
>   when:
>   ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 18
> 
> Perhaps this can be added to the repo?

This doesn't worked for me

**Comment by krzysztof-ksiazek** [comment]
Hi,

@optimadba, @bharathmsd7 Can you tell us what Ubuntu 18.04 do you use? What is the exact error that you are getting? The playbook installs python-mysqldb or python3-mysqldb instead of PyMySQL and it executes just fine on bento/ubuntu-18.04. 

```
- name: Making sure MySQL Python libraries are installed.
  apt: name=python-mysqldb state=present
  when:
    ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 18

- name: Making sure MySQL Python3 libraries are installed.
  apt: name=python3-mysqldb state=present
  when:
    ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 18
```
How did this step executed for you? We will need to understand better your environment to be able to tell what is wrong.
